addUser:
    path:     /adduser
    defaults: { _controller: DLUserBundle:User:addUser }

inscription:
    path:     /inscription
    defaults: { _controller: DLUserBundle:Inscription:register }

register1:
    path:     /{id}/addFiles
    defaults: { _controller: DLUserBundle:Registration:edit }

successadd:
    path:     /successadd
    defaults: { _controller: DLUserBundle:User:successadd }

mescommandes:
    path:     /mescommandes
    defaults: { _controller: DLUserBundle:commande:mescommandes }