

allProducts:
    path:     /dashboard/allProducts
    defaults: { _controller: DLAchatBundle:Produit:listProducts }

detailProduct:
    path:     /dashboard/{id}/detailProduct
    defaults: { _controller: DLAchatBundle:Produit:detailProduct }

ajouterPanier:
    path:     /dashboard/ajouterPanier
    defaults: { _controller: DLAchatBundle:Panier:ajouter }

supprimerPanier:
    path:     /dashboard/supprimerPanier
    defaults: { _controller: DLAchatBundle:Panier:supprimer }

panier:
    path:  /dashboard/panier
    defaults: { _controller: DLAchatBundle:Panier:panier }

commande:
    path:  /dashboard/{id}/commande
    defaults: { _controller: DLAchatBundle:Commande:addcommande }

achat:
    path:  /dashboard/{id}/achat
    defaults: { _controller: DLAchatBundle:Achat:addachat }

facture:
    path:  /dashboard/{id}/facture
    defaults: { _controller: DLAchatBundle:Main:facture}

facturationNetworker:
    path:  /dashboard/{id}/factureNetworker
    defaults: { _controller: DLAchatBundle:Commande:factureNetworker}

facturationClient:
    path:  /dashboard/{id}/factureClient
    defaults: { _controller: DLAchatBundle:Achat:factureClient}

listproduitaccueil:
    path:  /
    defaults: { _controller: DLFrontendBundle:Affichage:listProducts}

commandeadded:
    path:  /dashboard/commandepassee
    defaults: { _controller: DLAchatBundle:Commande:commandeadded}


panier_delete:
    path:     /dashboard/{id}/delete
    defaults: { _controller: DLAchatBundle:Commande:deletePanier }

facture_finale:
    path:     /dashboard/{id}/facturefinale
    defaults: { _controller: DLAchatBundle:Commande:facturefinale }