

allProducts:
    path:     /allProducts
    defaults: { _controller: DLAchatBundle:Produit:listProducts }

detailProduct:
    path:     /{id}/detailProduct
    defaults: { _controller: DLAchatBundle:Produit:detailProduct }

ajouterPanier:
    path:     /ajouterPanier
    defaults: { _controller: DLAchatBundle:Panier:ajouter }

supprimerPanier:
    path:     /supprimerPanier
    defaults: { _controller: DLAchatBundle:Panier:supprimer }

panier:
    path:  /panier
    defaults: { _controller: DLAchatBundle:Panier:panier }

commande:
    path:  /{id}/commande
    defaults: { _controller: DLAchatBundle:Commande:addcommande }

achat:
    path:  /{id}/achat
    defaults: { _controller: DLAchatBundle:Achat:addachat }

facture:
    path:  /{id}/facture
    defaults: { _controller: DLAchatBundle:Main:facture}

facturation:
    path:  /{id}/facturation
    defaults: { _controller: DLAchatBundle:Commande:facture}


