accueil:
    path:     /
    defaults: { _controller: DLFrontendBundle:Affichage:accueil }

actualite:
    path:     /actualite
    defaults: { _controller: DLFrontendBundle:Affichage:actualite }

contact:
    path:     /contact
    defaults: { _controller: DLFrontendBundle:Contact:createConctact }