

dashboard:
    path:     /dashboard
    defaults: { _controller: DLBackofficeBundle:Main:index }

tree:
    path:     /dashboard/tree
    defaults: { _controller: DLBackofficeBundle:Main:showtree }


event:
    path:     /dashboard/blog
    defaults: { _controller: DLBackofficeBundle:Main:event }

challenge:
    path:     /dashboard/challenges
    defaults: { _controller: DLBackofficeBundle:Main:challenge }

erreuradduser:
    path:     /dashboard/erreuradd
    defaults: { _controller: DLBackofficeBundle:Main:erreuradduser }

erreurarbre:
    path:     /dashboard/erreurarbre
    defaults: { _controller: DLBackofficeBundle:Main:erreurarbre }

mespartenaires:
    path:     /dashboard/mespartenairesG
    defaults: { _controller: DLBackofficeBundle:MesPartenaires:afficherpartenairesG }

mespartenaires2:
    path:     /dashboard/mespartenairesD
    defaults: { _controller: DLBackofficeBundle:MesPartenaires:afficherpartenairesD }