dl_backoffice_homepage:
    path:     /
    defaults: { _controller: DLBackofficeBundle:Default:index }

dashboard:
    path:     /dashboard
    defaults: { _controller: DLBackofficeBundle:Main:index }